name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: About Page
      id: about-page
      uses: education/autograding-command-grader@v1
      with:
        test-name: About Page
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
        command: pytest tests/test_about_page.py
        timeout: 10
        max-score: 5
    - name: Index Page
      id: index-page
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Bad password
      id: bad-password
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Dashboard
      id: dashboard
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Login Success
      id: login-success
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Login User not Found
      id: login-user-not-found
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Logout
      id: logout
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Profile Controller
      id: profile-controller
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Profile Model
      id: profile-model
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Test Registration Duplicate Fail
      id: test-registration-duplicate-fail
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt
    - name: Test Registration Success
      id: test-registration-success
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt
    - name: test_sample_authenticated_menu.py
      id: test_sample_authenticated_menu-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: test_sample_login_redirect.py
      id: test_sample_login_redirect-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: test_sample_model.py
      id: test_sample_model-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: test_sample_route.py
      id: test_sample_route-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: test_sample_unauthenticated_menu.py
      id: test_sample_unauthenticated_menu-py
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 25
        setup-command: sudo -H pip3 install -r requirements.txt && flask db upgrade
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        ABOUT-PAGE_RESULTS: "${{steps.about-page.outputs.result}}"
        INDEX-PAGE_RESULTS: "${{steps.index-page.outputs.result}}"
        BAD-PASSWORD_RESULTS: "${{steps.bad-password.outputs.result}}"
        DASHBOARD_RESULTS: "${{steps.dashboard.outputs.result}}"
        LOGIN-SUCCESS_RESULTS: "${{steps.login-success.outputs.result}}"
        LOGIN-USER-NOT-FOUND_RESULTS: "${{steps.login-user-not-found.outputs.result}}"
        LOGOUT_RESULTS: "${{steps.logout.outputs.result}}"
        PROFILE-CONTROLLER_RESULTS: "${{steps.profile-controller.outputs.result}}"
        PROFILE-MODEL_RESULTS: "${{steps.profile-model.outputs.result}}"
        TEST-REGISTRATION-DUPLICATE-FAIL_RESULTS: "${{steps.test-registration-duplicate-fail.outputs.result}}"
        TEST-REGISTRATION-SUCCESS_RESULTS: "${{steps.test-registration-success.outputs.result}}"
        TEST_SAMPLE_AUTHENTICATED_MENU-PY_RESULTS: "${{steps.test_sample_authenticated_menu-py.outputs.result}}"
        TEST_SAMPLE_LOGIN_REDIRECT-PY_RESULTS: "${{steps.test_sample_login_redirect-py.outputs.result}}"
        TEST_SAMPLE_MODEL-PY_RESULTS: "${{steps.test_sample_model-py.outputs.result}}"
        TEST_SAMPLE_ROUTE-PY_RESULTS: "${{steps.test_sample_route-py.outputs.result}}"
        TEST_SAMPLE_UNAUTHENTICATED_MENU-PY_RESULTS: "${{steps.test_sample_unauthenticated_menu-py.outputs.result}}"
      with:
        runners: about-page,index-page,bad-password,dashboard,login-success,login-user-not-found,logout,profile-controller,profile-model,test-registration-duplicate-fail,test-registration-success,test_sample_authenticated_menu-py,test_sample_login_redirect-py,test_sample_model-py,test_sample_route-py,test_sample_unauthenticated_menu-py
